### ISSUE TITLE
Implement handle() method in transaction handlers in Contracts module

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#4768] opened 2023-01-26 01:11 UTC
- [ ] ContractCallHandler
- [ ] ContractCreateHandler
- [ ] ContractDeleteHandler
- [ ] ContractSystemDeleteHandler
- [ ] ContractSystemUndeleteHandler
- [ ] ContractUpdateHandler
- [ ] EtherumTransactionHandler

**Comment by nickpoorman** [comment] 2023-05-31 17:19
Duplicate of https://github.com/hashgraph/hedera-services/issues/5520

**Closed by nickpoorman** 2023-05-31 17:19 UTC
Labels: Modularization
