### ISSUE TITLE
FCM-Migration-NewNodesFromGenesis-2.5k-8m is broken

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#9826] opened 2023-11-10 17:26 UTC
http://35.247.76.217:8095/swirlds-automation/develop/6N/Migration/20231110-090954-GCP-Daily-Migration-6N/FCM-Migration-NewNodesFromGenesis-2.5k-8m/

There are some problems with the migration test `FCM-Migration-NewNodesFromGenesis-2.5k-8m`. I am unsure if this is the result of a recently changed basis state, or if this is the result of a recent code change.

```
2023-11-10 09:17:03.222 20       ERROR MIGRATION        <main> MigrationTestingToolState: InitTrigger was GENESIS when expecting RESTART or RECONNECT
2023-11-10 09:17:03.222 21       ERROR MIGRATION        <main> MigrationTestingToolState: previousSoftwareVersion was null when expecting it to be 2
...
2023-11-10 09:17:39.106 216      ERROR MIGRATION        <<reconnect: reconnect-controller>> MigrationTestingToolState: previousSoftwareVersion was 3 when expecting it to be 2
```

**Comment by edward-swirldslabs** [comment] 2023-11-10 17:55
My current guess is that someone created a new state and advanced the version number on their branch, but didn't commit the version number advancement to develop.   This is the version numbers as they stand on develop for the migration testing tool: 
<img width="1381" alt="Screenshot 2023-11-10 at 11 53 53 AM" src="https://github.com/hashgraph/hedera-services/assets/123979964/0c4b7750-bb83-4614-bcb4-55c3d9151048">

In develop the current version is 3 and previous version is 2.   The code received a state for migration whose version was 3 when it should have been 2.

**Comment by alittley** [comment] 2023-11-13 16:36
There is a duplicate of this here https://github.com/hashgraph/hedera-services/issues/9336

**Comment by poulok** [comment] 2024-02-09 14:42
@edward-swirldslabs can this be closed?

**Comment by edward-swirldslabs** [comment] 2024-02-21 18:05
This can be closed

**Closed by edward-swirldslabs** 2024-02-21 18:05 UTC
