### ISSUE TITLE
Fix publishing to Maven Central for 0.53

### ISSUE THREAD

**Issue by jjohannes** [hashgraph/hedera-services#15149] opened 2024-08-27 17:26 UTC
Some things broke with when we changed the publishing setup to use the `io.github.gradle-nexus.publish-plugin` for Maven Central publishing. Looks like there are still issues.

**Comment by rbarkerSL** [comment] 2024-08-28 03:55
Duplicate of 15173

**Closed by rbarkerSL** 2024-08-28 03:55 UTC
