### ISSUE TITLE
Tests failed due to reconnect performance degradation

### ISSUE THREAD

**Issue by JeffreyDallas** [hashgraph/hedera-services#9518] opened 2023-10-26 16:09 UTC
### Description

A couple of tests failed 
 due to reconnect took longer to finish, seems like performance degradation

http://35.247.76.217:8095/swirlds-automation/develop/4N_2C/UpdateReconnect/20231026-063709-GCP-Daily-Update-Reconnect-4N-2C/Crypto-Update-ND-DisAftUpdate-RecPrePrepare-1.5k-25m/

```
---- ReconnectPerformanceValidator FAILED validation ----
<<ERROR>>
Reconnect took 10.129 seconds to transmit 13.995734214782715 mb.
```

Default threshold is 10 seconds for reconnect to finish

The previous test from commit #5f060e (Wed Oct 25) has no such error.

### Steps to reproduce

Nightly regression panel `GCP-Daily-Update-Reconnect-4N-2C`

### Hedera network

other

### Version

latest

### Operating system

None

**Comment by JeffreyDallas** [comment] 2023-10-26 16:09
https://swirldslabs.slack.com/archives/C03FD752LKA/p1698314479120049

https://swirldslabs.slack.com/archives/C03FD752LKA/p1698312934963339

**Comment by alittley** [comment] 2023-11-14 14:25
Failure observed multiple times in release 44:
- http://35.247.76.217:8095/swirlds-automation/release/0.44/6N/Migration/20231112-152840-GCP-Daily-Migration-6N/FCM-Migration-NewNodesFromGenesis-2.5k-8m/
- http://35.247.76.217:8095/swirlds-automation/release/0.44/6N/Migration/20231111-151331-GCP-Daily-Migration-6N/FCM-Migration-NewNodesFromGenesis-2.5k-8m/

**Comment by artemananiev** [comment] 2023-11-15 20:44
According to logs in http://35.247.76.217:8095/swirlds-automation/release/0.44/6N/Migration/20231111-151331-GCP-Daily-Migration-6N/FCM-Migration-NewNodesFromGenesis-2.5k-8m/swirlds-logs.html:

1. node4 started reconnect as a learner at 15:20:24
2. It took 15 seconds till 15:20:39 to receive the sub-tree at route []
3. Then 2 more seconds to receive the virtual tree at route [0 - 2 - 1], 15:20:41
4. Hashing the received tree took less than a second

Compared to successful test runs, like http://35.247.76.217:8095/swirlds-automation/release/0.44/6N/Migration/20231115-141909-GCP-Daily-Migration-6N/FCM-Migration-NewNodesFromGenesis-2.5k-8m/swirlds-logs.html, the difference is at step 2. When the test passes, step 2 is about 10 seconds.

**Comment by artemananiev** [comment] 2023-11-20 18:01
Since the logs are clear, and reconnect complete fine, the issue may be with validator config. I have just checked that config (threshold) for `FCM-Migration-NewNodesFromGenesis-2.5k-8m` have not been updated since 2020, while the size of the saved state to reconnect from have been at least doubled since then. I am going to increase the threshold slightly and keep an eye on it.

**Comment by alittley** [comment] 2024-01-08 17:04
Issue reoccurred

**Comment by artemananiev** [comment] 2024-01-09 20:08
New test failure analysis:

* Symptoms are similar to what was observed previously. No exceptions, no errors, it just takes too long
* Virtual map part is very fast, less than 2 seconds. The root part is what took the most time:

```
2024-01-08 14:25:08.596 67       INFO  RECONNECT        <<reconnect: reconnect-controller>> LearningSynchronizer: receiving tree rooted at com.swirlds.platform.state.State with route []
2024-01-08 14:25:28.257 79       INFO  RECONNECT        <<reconnect: reconnect-controller>> LearningSynchronizer: receiving tree rooted at com.swirlds.virtualmap.internal.merkle.VirtualRootNode with route [0 -> 2 -> 1]
2024-01-08 14:25:30.110 199      INFO  RECONNECT        <<reconnect: reconnect-controller>> LearningSynchronizer: synchronization complete
```

* There were other failures in the last few weeks (after the initial fix for this ticket was merged), so this is not a recent regression

**Comment by artemananiev** [comment] 2024-01-09 20:09
May be related: https://github.com/hashgraph/hedera-services/issues/8793

**Comment by artemananiev** [comment] 2024-01-24 18:07
Here is the current state of the test:

* With `develop`, the test has been passing for at least two weeks
* It fails intermittently with `0.46`, though

Since test configuration (reconnect timeouts to check by the validator) is identical in 0.46 and develop, it must be something it reconnect/hashgraph/virtualmap code in develop that eliminated the issue. 0.46 is out to testnet, there are no plans to backport these changes (which should be identified first) to that release. Re-closing the ticket.

**Closed by artemananiev** 2024-01-24 18:07 UTC
Labels: Bug
