### ISSUE TITLE
Test Negative Signatures Transfer

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#176] opened 2020-05-12 22:03 UTC

**Comment by qnswirlds** [comment] 2021-05-25 20:25
This issue has only the title. It doesn't have any description. We cannot understand the context of the issue here if we base only the title. I suggest we close this issue. @tinker-michaelj, @rbair23

**Comment by netopyr** [comment] 2024-06-12 10:06
Closed due to inactivity. Please reopen if you think the issue is still relevant.

**Closed by netopyr** 2024-06-12 10:06 UTC
Labels: P1, Test Development
