### ISSUE TITLE
COST reported in precheck error is incorrect

### ISSUE THREAD

**Issue by bugbytesinc** [hashgraph/hedera-services#13059] opened 2024-05-01 20:39 UTC
### Description

COST reported by precheck errors is insufficient to satisfy the minimum transaction fees for the transaction to complete.

### Steps to reproduce

execute a transaction with an insufficient max fee to get past precheck
assign the cost value returned from the precheck exception to the transaction attempt and retry
second attempt passes precheck but fails with insufficient transaction fee anyway.

### Additional context

```
    5/1/2024 7:46:16 PM  TX      → CRYPTOTRANSFER: 0.0.1282@1714592776.988337200
5/1/2024 7:46:16 PM  ├─ HEAD   { "transactionID": { "transactionValidStart": { "seconds": "1714592776", "nanos": 988337200 }, "accountID": { "accountNum": "1282" } }, "nodeAccountID": { "accountNum": "8" }, "transactionFee": "1", "transactionValidDuration": { "seconds": "120" } }
5/1/2024 7:46:16 PM  ├─ SIG    { "sigPair": [ { "pubKeyPrefix": "vQ==", "ed25519": "zHyPnxVeYAgl6lJjEdcgXt544+bpEZ7h6VggznPeF1w7IDkWiWVMp9rex/W9WgRn2idDEsY0CE5k042WuuR2Dw==" }, { "pubKeyPrefix": "0g==", "ed25519": "bsSIbV2/vjxIcHH+ZghnVCJUju8XcLkX2sZ/HJBlgWNIKjs4xwplVOkYxrflcKiZ+Fvvldx8zdDx2Pu13GcfCw==" } ] }
5/1/2024 7:46:16 PM  └─ BODY   { "cryptoTransfer": { "transfers": { "accountAmounts": [ { "accountID": { "accountNum": "4301394" }, "amount": "-10" }, { "accountID": { "accountNum": "1282" }, "amount": "10" } ] } } }
5/1/2024 7:46:17 PM  RX:(00)   { "nodeTransactionPrecheckCode": "INSUFFICIENT_TX_FEE", "cost": "147925" }
5/1/2024 7:46:17 PM  TX      → CRYPTOTRANSFER: 0.0.1282@1714592777.055960600
5/1/2024 7:46:17 PM  ├─ HEAD   { "transactionID": { "transactionValidStart": { "seconds": "1714592777", "nanos": 55960600 }, "accountID": { "accountNum": "1282" } }, "nodeAccountID": { "accountNum": "8" }, "transactionFee": "147925", "transactionValidDuration": { "seconds": "120" } }
5/1/2024 7:46:17 PM  ├─ SIG    { "sigPair": [ { "pubKeyPrefix": "vQ==", "ed25519": "sFLGUfQ0TnlwBDYtJaZ0cUnlqiFq9Oo0dj3nLz/LR/bCWcM/qeKjVEglkqCHuPZeXObzUNa2wUIh8Myr/135AA==" }, { "pubKeyPrefix": "0g==", "ed25519": "JzYXueaaLlF6EquRplWxJJ72Gh8xNZ4v8ptd0A7mgBmzsDiwKxkgn1K4lJkovGClwlK22dS23M4utWBKD2QiDg==" } ] }
5/1/2024 7:46:17 PM  └─ BODY   { "cryptoTransfer": { "transfers": { "accountAmounts": [ { "accountID": { "accountNum": "4301394" }, "amount": "-10" }, { "accountID": { "accountNum": "1282" }, "amount": "10" } ] } } }
5/1/2024 7:46:17 PM  RX:(00)   { }
5/1/2024 7:46:17 PM  RECEIPT   { "transactionGetReceipt": { "transactionID": { "transactionValidStart": { "seconds": "1714592777", "nanos": 55960600 }, "accountID": { "accountNum": "1282" } } } }
5/1/2024 7:46:17 PM  RX:(00)   { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
5/1/2024 7:46:17 PM  RX:(01)   { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
5/1/2024 7:46:17 PM  RX:(02)   { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
5/1/2024 7:46:17 PM  RX:(03)   { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
5/1/2024 7:46:17 PM  RX:(04)   { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
5/1/2024 7:46:18 PM  RX:(05)   { "transactionGetReceipt": { "header": { }, "receipt": { "status": "INSUFFICIENT_TX_FEE", "exchangeRate": { "currentRate": { "hbarEquiv": 30000, "centEquiv": 298533, "expirationTime": { "seconds": "1714593600" } }, "nextRate": { "hbarEquiv": 30000, "centEquiv": 323281, "expirationTime": { "seconds": "1714597200" } } } } } }
```

### Hedera network

testnet

### Version

Latest

### Operating system

None

**Comment by tinker-michaelj** [comment] 2024-05-06 15:52
Duplicate of https://github.com/hashgraph/hedera-services/issues/12958

**Closed by tinker-michaelj** 2024-05-06 15:52 UTC
Labels: Bug
