### ISSUE TITLE
HalfDiskHashMap: Unknown bucket field 2

### ISSUE THREAD

**Issue by edward-swirldslabs** [hashgraph/hedera-services#12311] opened 2024-03-22 18:23 UTC
There are a variety of errors in this failed JRS test: http://35.247.76.217:8095/swirlds-automation/release/0.47/4N/Reconnect/20240322-091133-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/

But in particular, this exception I have never seen before and it precedes the reconnect failure exceptions:  
```

HalfDiskHashMap: | Failed to read / update bucket
java.lang.IllegalArgumentException: Unknown bucket field: 2 	
at com.swirlds.merkledb.files.hashmap.Bucket.readFrom(Bucket.java:334) ~[swirlds-merkledb-0.47.0-SNAPSHOT.jar:?] 	
at com.swirlds.merkledb.files.hashmap.BucketSerializer.deserialize(BucketSerializer.java:142) ~[swirlds-merkledb-0.47.0-SNAPSHOT.jar:?] 	
at com.swirlds.merkledb.files.hashmap.BucketSerializer.deserialize(BucketSerializer.java:35) ~[swirlds-merkledb-0.47.0-SNAPSHOT.jar:?] 	
at com.swirlds.merkledb.files.DataFileCollection.readDataItem(DataFileCollection.java:526) ~[swirlds-merkledb-0.47.0-SNAPSHOT.jar:?] 	
at com.swirlds.merkledb.files.DataFileCollection.retryReadUsingIndex(DataFileCollection.java:550) ~[swirlds-merkledb-0.47.0-SNAPSHOT.jar:?] 	
at com.swirlds.merkledb.files.DataFileCollection.readDataItemUsingIndex(DataFileCollection.java:636) ~[swirlds-merkledb-0.47.0-SNAPSHOT.jar:?] 	
at com.swirlds.merkledb.files.hashmap.HalfDiskHashMap.readUpdateQueueBucket(HalfDiskHashMap.java:485) ~[swirlds-merkledb-0.47.0-SNAPSHOT.jar:?] 	
at com.swirlds.merkledb.files.hashmap.HalfDiskHashMap.lambda$endWriting$2(HalfDiskHashMap.java:433) ~[swirlds-merkledb-0.47.0-SNAPSHOT.jar:?] 	
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?] 	
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?] 	
at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]


```

**Comment by poulok** [comment] 2024-04-01 16:44
We will leave this ticket open for 2 weeks to see if it reproduces. If it does not, this ticket will be closed.

**Comment by lpetrovic05** [comment] 2024-04-09 16:48
new reproduction http://35.247.76.217:8095/swirlds-automation/release/0.48/4N/Reconnect/20240406-094257-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/

**Comment by poulok** [comment] 2024-04-15 16:49
New Plan - run this test continuously and download the state for every run. If the validator succeeds, delete the state. Next time it fails, we will have the state to analyze.

**Comment by artemananiev** [comment] 2024-04-16 00:18
One more failure with 0.49: http://35.247.76.217:8095/swirlds-automation/release/0.49/4N/Reconnect/20240412-094024-GCP-Daily-Reconnect-4N/

**Comment by edward-swirldslabs** [comment] 2024-04-16 16:43
Another failure on develop : http://35.247.76.217:8095/swirlds-automation/develop/4N/Reconnect/20240416-053857-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/

**Comment by poulok** [comment] 2024-05-13 16:05
@Artem setup a regression branch that downloads the state on every run and deletes it if the validators fail. We need to get a state where this failure occurs but have been unable to so far.

**Comment by poulok** [comment] 2024-05-20 16:29
@Artem and @JeffreyDallas will work to shutdown the test as soon as this exception appears in the logs so that the files with the problem are not deleted during compaction. Then we need another reproduction to continue debugging.

**Comment by kfa-aguda** [comment] 2024-05-20 17:49
We've noticed this issue in today's JRS test from release branch 50
http://35.247.76.217:8095/swirlds-automation/release/0.50/4N/Reconnect/20240520-101326-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/

**Comment by kfa-aguda** [comment] 2024-05-21 17:15
Noticed today as well. Just noting it. http://35.247.76.217:8095/swirlds-automation/release/0.50/4N/Reconnect/20240521-101041-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/

we will be ignoring as the issue gets worked on as discussed here.

**Comment by artemananiev** [comment] 2024-10-17 22:44
The root cause for this bug is finally found. Here is the sequence:

* A node is running as usual. It has a virtual map, a new copy of the map is created every round, the copies are added to the virtual pipeline, which hashes/merges/flushes them in background
* At some point, the node falls behind the network and starts a reconnect
* In the beginning of the reconnect, a snapshot of the virtual map is created. The snapshot has two components: data source snapshot (using VirtualDataSourceBuilder.copy() method) and node cache snapshot (by flushing the cache to the data source copy)
* When the snapshot is taken, there may be a map flush in process, since flushes are running in background on a separate (virtual map lifecycle) thread
* During the flush, a new file is created for HalfDiskHashMap (object key to path mapping). However, the file is not included to the snapshot, since it's not written completely. See `DataFileCollection.snapshot()` for details
* However, HalfDiskHashMap index is included to the snapshot. Some entries in the index point to the new file, which will not be in the snapshot. A problem
* After data source snapshot is ready, the next step is to flush the node cache to it. This is where the original bug actually happens. During this flush, a new HalfDiskHashMap file is created. It has the same index as the new file, which is being written during the flush above. This is very confusing
* To write an updated bucket to the new HalfDiskHashMap file, the existing bucket must be read from disk. If this bucket was updated in the flush above, the index will point to a wrong file. File index is the same, but it's entirely different file. This is where some random bytes are read, and this is when bucket parsing fails

The root cause is that snapshots are not synchronized with flushes during reconnects. For regular snapshots (taken every 15 mins or so), synchronization is there: we let current merge/flush in progress (if any) complete, then take a snapshot. See `VirtualPipeline.detachCopy()` for details. So this problem is specific to reconnects

**Comment by edward-swirldslabs** [comment] 2024-10-18 18:31
@artemananiev Is the solution simple?

**Comment by artemananiev** [comment] 2024-10-30 20:18
The fix is included to https://github.com/hashgraph/hedera-services/pull/16090

**Closed** 2024-12-10 17:46 UTC
Labels: Platform Reconnect, Platform Virtual Map, Platform Data Structures, Platform, Stability
