### ISSUE TITLE
Previewnet regression: NEGATIVE NFT serial numbers

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/hedera-services#12913] opened 2024-04-21 18:32 UTC
### Description

A user (@bugbytes) reported the following transaction on Previewnet (v0.49.0-alpha.5):
https://hashscan.io/previewnet/transaction/1713699425.061252957
Notice that:
- The method being called was to update a token record, not transfer an NFT
- A negative (-1) NFT serial being transferred

<img width="1427" alt="image" src="https://github.com/hashgraph/hedera-services/assets/72571340/bb542fee-d1a1-48ee-8507-841a9d10cc86">

cc: @tinker-michaelj @netopyr @Neeharika-Sompalli FYI

### Steps to reproduce

This issue has been shared with the user to share details for reproduction of the observed results.

### Hedera network

previewnet

### Version

v0.49.0-alpha.5

### Operating system

None

**Comment by Neeharika-Sompalli** [comment] 2024-04-21 20:33
It seems like this transaction is updating treasury on the token. 
So all the NFTs of the previous treasury are in a sense transferred to new treasury. The record includes this transfer of a sentinel serial number -1 in this case, to trigger mirror nodes to update the owned NFT counts. So this is expected behavior.

```
consensusTime=2024-04-21T11:37:05.061252957Z, txn=transactionID {
  transactionValidStart {
    seconds: 1713699424
    nanos: 725751400
  }
  accountID {
    accountNum: 1090
  }
}
nodeAccountID {
  accountNum: 8
}
transactionFee: 6000000000
transactionValidDuration {
  seconds: 120
}
tokenUpdate {
  token {
    tokenNum: 3549
  }
  symbol: "75HopCXK-WinIjVMwYX3INqYeDGhD2@MT4VaBJD*6d$@5nQapwDL#R52gHNa@TXI-H%eSWf9frQ44E2iwHVVvNUD6dVB$XfWOHeL"
  name: "L$8uTHsftS!aFsF5SisiJ&3dZn&xeRU*RslRjGfSeF7e"
  treasury {
    accountNum: 3550
  }
  adminKey {
    ECDSA_secp256k1: "\003H\347\022\215RQK\365\243\032\303Z\331X\343\333\3314\311\261\256\262v\333\031\b\213\205t\003r6"
  }
  kycKey {
    ECDSA_secp256k1: "\002\333\334$\221\277\207=\240\036\304\323\020\361l\317\304\274=)\262\222\273gL\232[\021\362\020\353\250\376"
  }
  freezeKey {
    ed25519: "\367\251Q\227\353B\353\034\377\243\203\237\307y{\\o`ZY\215\312\311\222a\"\361vp\306\016\217"
  }
  wipeKey {
    ECDSA_secp256k1: "\002\355N\373\327\001\026\224\220Xj%\321\203\261D|\251\021\301\037\232\335\346\365\'\303\270\001\220\255\354M"
  }
  supplyKey {
    ed25519: "\f\351D\f\223\222\005\372\360&\247C\200\362\253z\226i\357\350\023\371\v\004\321R\370}\001P]G"
  }
  autoRenewAccount {
    accountNum: 3551
  }
  autoRenewPeriod {
    seconds: 7776000
  }
  expiry {
    seconds: 1729251424
    nanos: 787460000
  }
  memo {
    value: "Test Asset: 8uFX$ScdPT0iI#v#F-vn"
  }
  pause_key {
    ed25519: "\241\272\356\333\245/\222\215\376\327\226\362\266<\352Y\273\fGs\304,\372\220l \253q\335\006\325\360"
  }
}



record=receipt {
  status: SUCCESS
  exchangeRate {
    currentRate {
      hbarEquiv: 1
      centEquiv: 12
      expirationTime {
        seconds: 4102444800
      }
    }
    nextRate {
      hbarEquiv: 1
      centEquiv: 15
      expirationTime {
        seconds: 4102444800
      }
    }
  }
}
transactionHash: "\030=\300\340\207\344\017\026\211\356\267\226\367_\037\027Vf,\242\003\326\2609^Wj\323\232K\2344\320\205\035\330\235,@\364\214nZ\201\030\224\221K"
consensusTimestamp {
  seconds: 1713699425
  nanos: 61252957
}
transactionID {
  transactionValidStart {
    seconds: 1713699424
    nanos: 725751400
  }
  accountID {
    accountNum: 1090
  }
}
transactionFee: 4017759
transferList {
  accountAmounts {
    accountID {
      accountNum: 8
    }
    amount: 52410
  }
  accountAmounts {
    accountID {
      accountNum: 98
    }
    amount: 3568815
  }
  accountAmounts {
    accountID {
      accountNum: 800
    }
    amount: 396534
  }
  accountAmounts {
    accountID {
      accountNum: 1090
    }
    amount: -4017759
  }
}
tokenTransferLists {
  token {
    tokenNum: 3549
  }
  nftTransfers {
    senderAccountID {
      accountNum: 3547
    }
    receiverAccountID {
      accountNum: 3550
    }
    serialNumber: -1
  }
}
}

```

**Comment by bugbytesinc** [comment] 2024-04-22 18:10
This breaks the HAPI contract at the gRPC level when records are returned.

**Comment by bugbytesinc** [comment] 2024-04-22 18:21
This could also throw off tax computation software, or at least makes it unduly more complicated.

**Comment by Neeharika-Sompalli** [comment] 2024-04-22 19:03
Thank you @bugbytesinc. 
Yes, I agree. This has been the the behavior for treasury changes in `TokenUpdate`. I will open an issue to discuss this and modify this behavior in future release.

**Comment by Neeharika-Sompalli** [comment] 2024-04-23 15:09
@ed-marquez @bugbytesinc  I have created an issue to discuss in the future #12936 . Will close this issue for now, since it cannot be fixed in this release.

**Closed** 2024-04-23 19:37 UTC
