### ISSUE TITLE
JRS Failure: VMerkleDual-NDReconnect-500-60m State file not found

### ISSUE THREAD

**Issue by edward-swirldslabs** [hashgraph/hedera-services#9161] opened 2023-10-10 18:03 UTC
http://35.247.76.217:8095/swirlds-automation/release/0.43/4N/Reconnect/20231010-094120-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/summary.txt

This test is failing in branch 0.43

related issue: 
#8237

**Comment by edward-swirldslabs** [comment] 2023-10-31 18:18
Still Happening.  http://35.247.76.217:8095/swirlds-automation/release/0.43/4N/Reconnect/20231031-094334-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/summary.txt

@imalygin, is there a fix planned for branch .43?

**Comment by imalygin** [comment] 2023-11-01 14:14
Investigating.

**Comment by imalygin** [comment] 2023-11-01 17:51
JRS validation fails because `VirtualMerkleLeafHasher` doesn't create `vmapHashes.json` file in some cases. `VirtualMerkleLeafHasher` with the following error:

```
Exception in thread "main" java.lang.IllegalArgumentException: path (7016275) is not valid; must be in range (11229233,22458466)
	at com.swirlds.merkledb.MerkleDbDataSource.loadLeafRecord(MerkleDbDataSource.java:694)
	at com.swirlds.virtualmap.internal.merkle.VirtualInternalNode.getLeafNode(VirtualInternalNode.java:207)
	at com.swirlds.virtualmap.internal.merkle.VirtualInternalNode.getChild(VirtualInternalNode.java:154)
	at com.swirlds.virtualmap.internal.merkle.VirtualInternalNode.getLeft(VirtualInternalNode.java:138)
	at com.swirlds.virtualmap.internal.merkle.VirtualInternalNode.getChild(VirtualInternalNode.java:88)
	at com.swirlds.common.merkle.iterators.MerkleIterator.pushNode(MerkleIterator.java:244)
	at com.swirlds.common.merkle.iterators.internal.BreadthFirstAlgorithm.pushChildren(BreadthFirstAlgorithm.java:77)
	at com.swirlds.common.merkle.iterators.MerkleIterator.findNext(MerkleIterator.java:312)
	at com.swirlds.common.merkle.iterators.MerkleIterator.hasNext(MerkleIterator.java:326)
	at com.swirlds.demo.virtualmerkle.VirtualMerkleLeafHasher.validate(VirtualMerkleLeafHasher.java:82)
	at com.swirlds.demo.virtualmerkle.VirtualMerkleLeafHasher.main(VirtualMerkleLeafHasher.java:188)
```

However, it's not clear where this VM path comes from given the fact that for every round `VirtualMerkleLeafHasher` calls `MerkleDb.resetDefaultInstancePath()`. This call should result in creation of a new instance of MerkleDB with empty metadata.

**Comment by imalygin** [comment] 2023-12-12 20:37
This bug is notoriously hard to reproduce, so I made a change in the platform regression framework to upload the state whenever it fails with this exception. Now we wait.

https://github.com/swirlds/swirlds-platform-regression/pull/3862
https://github.com/swirlds/swirlds-platform-regression/pull/3863

**Comment by imalygin** [comment] 2024-01-10 15:39
pushed one more change related to this issue 
https://github.com/swirlds/swirlds-platform-regression/pull/3881

**Comment by poulok** [comment] 2024-01-22 17:16
We are currently waiting for a reproduction

**Comment by edward-swirldslabs** [comment] 2024-01-25 18:30
Latest Failure: http://35.247.76.217:8095/swirlds-automation/release/0.46/4N/Reconnect/20240125-091133-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/summary.txt

**Comment by poulok** [comment] 2024-02-26 17:22
Reevaluate on March 11

**Comment by poulok** [comment] 2024-03-11 16:26
Closing this ticket because this failure has not been seen in several weeks.

**Closed by poulok** 2024-03-11 16:26 UTC
