### ISSUE TITLE
Run thorough performance testing with the PBJ DataIO enabled

### ISSUE THREAD

**Issue by jsync-swirlds** [hashgraph/hedera-services#5599] opened 2023-03-10 19:38 UTC

**Comment by artemananiev** [comment] 2024-01-11 23:29
Low-level virtual map benchmarks showed 20-25% regression with MerkleDb PBJ branch. It was addressed in a few PRs, e.g. https://github.com/hashgraph/hedera-services/issues/9942. Now PBJ backend as fast as JDB backend was previously in develop (but JDB is now slightly slower; it shouldn't be a big issue, since JDB will be dropped shortly).

High-level Hedera services performance test results are still pending.

**Comment by artemananiev** [comment] 2024-04-02 21:49
Done

**Closed by artemananiev** 2024-04-02 21:49 UTC
Labels: Performance
