### ISSUE TITLE
Epic: Implement the `hedera-file-service` modules

### ISSUE THREAD

**Issue by rbair23** [hashgraph/hedera-services#4215] opened 2022-11-08 01:11 UTC
- [x] #4456
- [x] https://github.com/hashgraph/hedera-services/issues/4028
- [x] #4455 
- [x] https://github.com/hashgraph/hedera-services/issues/4051
- [x] https://github.com/hashgraph/hedera-services/issues/4255

**Comment by nickpoorman** [comment] 2023-04-18 21:03
Duplicate of https://github.com/hashgraph/hedera-services/issues/5517

**Closed by nickpoorman** 2023-04-18 21:03 UTC
Labels: Epic, Modularization
