### ISSUE TITLE
Token Test Scenarios Failing

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-services#906] opened 2020-12-31 22:51 UTC
**Summary of the defect**
Token test scenarios failing in test `Misc-Basic-1-11m.json`
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1609263264345900
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1609445428398600

**Service logs (if applicable)**
```
[hapi-client-combined.log](https://github.com/hashgraph/hedera-services/files/5758419/hapi-client-combined.log)

```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by ljianghedera** [comment] 2021-01-22 04:02
Find the root cause and the problem should be fixed.

**Closed** 2021-01-25 17:21 UTC
Labels: Test Development
