### ISSUE TITLE
Testing plan for account auto renewal/removal

### ISSUE THREAD

**Issue by qnswirlds** [hashgraph/hedera-services#1225] opened 2021-04-03 17:42 UTC
**HIP:** https://github.com/hashgraph/hedera-improvement-proposal/blob/master/HIP/hip-16.md
**Design doc:** https://github.com/hashgraph/hedera-services/blob/master/docs/autorenew-feature.md

---

Set `minimumAutoRenewDuration=10` for fast tests
Set `autorenew.gracePeriod=0` for all tests except for the test of gracePeriod
- [x] Test account auto removal
 1. Create an account with minimum `autoRenewPeriod` allowed, with zero balance.
 2.  Sleep to pass the minimum `autoRenewPeriod` allowed
 3. Perform a transaction to trigger the account auto removal
 4. Get account balance should receive `INVALID_ACCOUNT_ID` precheck status because the account was automatically removed

- [x] Test account auto renewal
1. Create an account with minimum `autoRenewPeriod` allowed, with an initial balance of 100 hbars
2. Sleep to pass the `autoRenewPeriod`
3. Perform a transaction to trigger the account auto renewal
4. Get account balance should see a balance less than 100 hbars because the account was charged for auto renewal
5. Get account info should see a new `expirationTime` 

- [x] Test `autorenew.maxNumberOfEntitiesToRenewOrDelete` setting:
1. Set `autorenew.numberOfEntitiesToScan=100`
2. Set `autorenew.maxNumberOfEntitiesToRenewOrDelete=2`
3. Create 4 accounts with minimum `autoRenewPeriod` allowed, all with zero balance, except that the last one has 100 hbars
4. Sleep to pass the minimum `autoRenewPeriod` allowed
5. Perform a transaction to trigger the account auto renewal/removal
6. Get account balance of the first 2 accounts created should receive `INVALID_ACCOUNT_ID` precheck status because the accounts were automatically removed
7. Get account balance of the last 2 accounts created should be successful
8. Perform another transaction to trigger another round of account auto renewal/removal
9. Get account balance of the second last account should receive `INVALID_ACCOUNT_ID` precheck status because the account was automatically removed
10. Get account balance of the last account should see a balance less than 100 hbars because the account was charged for auto renewal

- [x] Test `autorenew.numberOfEntitiesToScan` setting:
1. Set `autorenew.numberOfEntitiesToScan=100`
2. Set `autorenew.maxNumberOfEntitiesToRenewOrDelete=2`
3. Create `autorenew.numberOfEntitiesToScan` accounts with normal (long) `autoRenewPeriod`
4. Create 2 more accounts with minimum `autoRenewPeriod` allowed, one with zero balance, and the last one has 100 hbars
5. Sleep to pass the minimum `autoRenewPeriod` allowed
6. Perform a transaction to trigger the account auto renewal/removal
7. Get account balance of the last 2 accounts created should be successful
8. Perform another transaction to trigger another round of account auto renewal/removal
9. Get account balance of the second last account should receive `INVALID_ACCOUNT_ID` precheck status because the account was automatically removed
10. Get account balance of the last account should see a balance less than 100 hbars because the account was charged for auto renewal

- [x] Test `autorenew.gracePeriod` setting:
1. Set `autorenew.gracePeriod=120` (2 minutes)
2. Create an account with minimum `autoRenewPeriod` allowed, with zero balance
3. Sleep to pass the minimum `autoRenewPeriod` allowed, but not pass the `autorenew.gracePeriod=120` yet
4. Perform a transaction to trigger the account auto renewal/removal
5. Get account balance should be successful
6. Sleep to pass also the `autorenew.gracePeriod=120`
7. Perform another transaction to trigger another round of account auto renewal/removal
8. Get account balance should receive `INVALID_ACCOUNT_ID` precheck status because the account was automatically removed

- [x] For reconnect:
1. Create an account with small `autoRenewPeriod`, with zero balance
2. Disconnect a node
3. Sleep to pass the `autoRenewPeriod`
4. Perform a transaction to trigger the account auto removal while one node is still disconnected
5. The disconnected node reconnects to the network. Get account balance from this node should receive `INVALID_ACCOUNT_ID` precheck status because the account was automatically removed

_Grace period restrictions_
- [x] No token interaction (become/renounce treasury, associate/dissociate, freeze/unfreeze, grant/revoke kyc) 
- [x] No crypto transfers (ℏ or token)
- [x] No use as payer of txn or query
- [x] No auto-renew assignment changes 
- [x] No reference in a `CryptoDelete`.
- [x] No `CryptoUpdate` changes **other than expiry extension**.
- [x] No designation as scheduled txn payer.
- [x] No interaction with smart contracts.

_But,_
- [x] No restrictions are enforced unless `autoRenew.isEnabled=true`.

_Removal of a non-treasury account with token units_
- [x] Units of a deleted token are burned
- [x] Units of any other token are returned to its treasury 

(In all cases the account's entries are removed from the `tokenAssociations` FCM.)

_Expected treatment of contracts and deleted accounts_
- [x] Ignores expiration of contract accounts.
- [x] Immediately removes deleted accounts at expiration (no grace period).

_Fees charged are consistent with renewal events_
- [x] Let `0.0.X` be an account with an `autoRenewPeriod` of 2 seconds and an initial expiry of `T`. After a 30-second burst of `CryptoTransfer`s traffic, it should be renewed some number of times. If the fee per renewal is `F`, then given a new expiry of `U` after the 30-second burst, the `0.0.X` balance must decrease by `F * (U - T) / 2` tinybar.

**Comment by anighanta** [comment] 2021-04-28 18:05
- [ ] A Hedera entity can have its expiration time extended by anyone

- Set `autorenew.gracePeriod=120`.
- Create a crypto account `autoRenewAccount` with minimum autoRenewPeriod allowed and zero balance.
- Create a crypto account `payer` with 100 hbars.
- Sleep to pass the autoRenewPeriod.
- Perform a transaction to trigger the account auto renewal/removal round and push `autoRenewAccount` into grace period.
- verify that we cannot update any other fields except for `expiration time` on `autoRenewAccount` when it is in its grace period.
- Perform a `cryptoUpdate` on `autoRenewAccount` updating its `expiration time` and paid by `payer`.
- Get account balance on `payer` should see a balance less than 100 hbars because the account was charged for auto renewal.
- Get account info on  `autoRenewAccount` should see a new expirationTime

**Comment by rbair23** [comment] 2021-04-28 20:58
Make sure that enablement and disablement of this feature works. We will release it in 0.14.0 but enable it later. Also make sure to make sure that when disabled, it doesn't cause any performance regressions.

**Comment by noshmody** [comment] 2021-04-29 13:39
With auto-renew there will be 2 delete conditions for an entity.

1. User Deletion - entity is marked as deleted and removed at expiration (no grace period)
2. Auto Deletion - entity has expired, removed after grace period

Will / should these 2 conditions be identified differently on the entity?
If yes then we need a flag that marks the entity as expired (rather than deleted)
If yes then can the entity be queried during the grace period?

Will require migration testing since we will be changing state at restart.

**Closed** 2021-05-11 17:49 UTC
Labels: P1, Test Development
