### ISSUE TITLE
Implement `AdminService`'s `handle()`-methods

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#4465] opened 2022-12-09 15:48 UTC
### Problem

We need a handle()-methods:

- [ ] AdminFreezeHandler.handle()

### Solution

Implement the above.

**Comment by nickpoorman** [comment] 2023-04-19 21:40
Duplicate of https://github.com/hashgraph/hedera-services/issues/6195

**Closed by nickpoorman** 2023-04-19 21:40 UTC
Labels: Modularization
