### ISSUE TITLE
File-Recovery-EvSave15sTrunc-5-21m : Failure in swirlds.log

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-services#1695] opened 2021-06-28 19:47 UTC
**Summary of the defect**
`File-Recovery-EvSave15sTrunc-5-21m` fails with `java.util.NoSuchElementException`

Test successfully handles transactions and writes states to disc but fails to restart. 

**Service logs (if applicable)**
```
2021-06-27 08:50:31.094 27       DEBUG STARTUP          <main> SwirldsPlatform: Platform has loaded a saved state {"round":2,"consensusTimestamp":{"nano":989525000,"epochSecond":1624783483},"willFreezeUntil":{"nano":82963000,"epochSecond":1624783841}} [com.swirlds.logging.payloads.SavedStateLoadedPayload]
2021-06-27 08:50:31.099 28       ERROR EXCEPTION        <main> Browser: 
java.util.NoSuchElementException: Missing generation for round -23
	at com.swirlds.platform.eventhandling.MinGenQueue.getRoundGeneration(MinGenQueue.java:92) ~[swirlds-platform-core-0.16.0-alpha.1.jar:?]
	at com.swirlds.platform.EventFlow.loadDataFromSignedState(EventFlow.java:529) ~[swirlds-platform-core-0.16.0-alpha.1.jar:?]
	at com.swirlds.platform.SwirldsPlatform.buildEventFlow(SwirldsPlatform.java:907) ~[swirlds-platform-core-0.16.0-alpha.1.jar:?]
	at com.swirlds.platform.SwirldsPlatform.initializeFirstStep(SwirldsPlatform.java:777) ~[swirlds-platform-core-0.16.0-alpha.1.jar:?]
	at com.swirlds.platform.Browser.startPlatforms(Browser.java:982) ~[swirlds-platform-core-0.16.0-alpha.1.jar:?]
	at com.swirlds.platform.Browser.main(Browser.java:364) [swirlds-platform-core-0.16.0-alpha.1.jar:?]
```
**Additional Context**
[slack link ](https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1624784556138600)
[summary link](https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1624784601113300)

**Comment by anighanta** [comment] 2021-06-28 19:48
Need to check with platform team.

**Comment by tinker-michaelj** [comment] 2021-06-28 21:58
Duplicate of #1634

**Closed by tinker-michaelj** 2021-06-28 21:58 UTC
Labels: Regression, bug
