### ISSUE TITLE
New reconnect metrics based on ReconnectNodeCount collected stats

### ISSUE THREAD

**Issue by artemananiev** [hashgraph/hedera-services#11432] opened 2024-02-07 20:27 UTC
`ReconnectNodeCount` interface is used to collect various stats about reconnects, in particular number of leaf/internal nodes transferred, and number of nodes that were redundant. This collected information goes nowhere, but instead should be exposed as a set of platform metrics.

**Comment by poulok** [comment] 2024-06-10 19:15
Duplicate of #12412

**Closed by poulok** 2024-06-10 19:15 UTC
Labels: Platform Reconnect, Platform Data Structures, Platform, Observability
