### ISSUE TITLE
Provide DA demo for HIP-564 (zero-unit token operations)

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#4079] opened 2022-10-17 16:18 UTC
### Problem

We need examples to clarify the functional changes from HIP-564, which allows several token operations to behave as no-ops when given zero units.

### Solution

Use a standard SDK with a few introductory slides to give DA's working examples of the HIP-564 functional impact.

**Comment by Neeharika-Sompalli** [comment] 2022-10-17 20:57
Duplicate of https://github.com/hashgraph/hedera-services/issues/4073

**Closed by Neeharika-Sompalli** 2022-10-17 20:57 UTC
