### ISSUE TITLE
Flaky QueueThread Test

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#6277] opened 2023-04-27 14:01 UTC
Test flake observed. We need to investigate and make this test more robust.

https://github.com/hashgraph/hedera-services/actions/runs/4819587226/jobs/8582993022?pr=6263

![Screenshot 2023-04-27 at 9 00 49 AM](https://user-images.githubusercontent.com/56973212/234885762-1d658db5-a5c0-4a02-b449-b018caa0f112.png)

**Comment by edward-swirldslabs** [comment] 2023-06-27 16:41
Closing for the following reasons: 
1. Not able to reproduce locally
2. The attached logs have expired
3. Critical code paths have been modified (5/19/23 @lpetrovic05 updated the metrics with busy time version) 
4. Analyzing the test, the only triage would be to increase the sleep time in the unit test to give the handler more time to drain the queue.   The issue has not come up recently.  The failure may have been on a particularly stressed VM.

**Closed** 2023-06-27 16:42 UTC
Labels: Tech Debt Reduced
