### ISSUE TITLE
Change default ISS settings

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#7047] opened 2023-06-12 14:17 UTC
Change the following settings to be the default:

```
state.automatedSelfIssRecovery, true
state.haltOnCatastrophicIss,    true
```

The net effect of these settings is that nodes with an ISS will write a state snapshot then power down, as long as the ISS is not catastrophic. In the event of a catastrophic ISS, all nodes will save a state snapshot, and then will stop gossiping without shutting down.

Before making this change, consult with devops and release engineering and ensure that they all understand the new behavior.

**Comment by poulok** [comment] 2023-07-05 15:08
duplicate of #7206

**Closed by poulok** 2023-07-05 15:08 UTC
