### ISSUE TITLE
Migration test starting from genesis

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#9336] opened 2023-10-18 14:48 UTC
http://35.247.76.217:8095/swirlds-automation/develop/6N/Migration/20231017-090649-GCP-Daily-Migration-6N/FCM-Migration-NewNodesFromGenesis-2.5k-8m/

The following error message appears in all logs in this test:

```
InitTrigger was GENESIS when expecting RESTART or RECONNECT
```

Most likely due to recent changes related to the consensus algorithm, the migration test now appears to be using genesis pathways instead of using migration pathways.

**Comment by alittley** [comment] 2023-11-13 15:59
Reoccurred http://35.247.76.217:8095/swirlds-automation/release/0.43/6N/Migration/20231112-145700-GCP-Daily-Migration-6N/FCM-Migration-NewNodesFromGenesis-2.5k-8m/

**Comment by edward-swirldslabs** [comment] 2023-11-13 17:05
The issue I created on Friday was for the same failure in develop, but it passed on Saturday and Sunday.   Is it possible that the test framework is failing to load the right state and is starting the test with no state, i.e. a genesis start, and that is what is causing this failure?

**Comment by edward-swirldslabs** [comment] 2023-11-13 18:03
Here is what is going on: 

Test Scenario:  nodes 0-3 get the migration state.   Nodes 4,5 start from genesis.   This test has been this way since '22

Nodes 4,5 have always been logging an error at this point:
https://github.com/hashgraph/hedera-services/blob/03614b661a7ab33e4d27251992d080bcabd38fe7/platform-sdk/platform-apps/tests/MigrationTestingTool/src/main/java/com/swirlds/demo/migration/MigrationTestingToolState.java#L242-L244

The JRS Test Framework is ignoring these logged errors on 4/5 when the test passes, and being sensitive to the logged errors when the test is reported as failing to pass. 

Here is a test that passed, but nodes 4 and 5 are still logging their errors: 
http://35.247.76.217:8095/swirlds-automation/release/0.43/6N/Migration/20231111-145908-GCP-Daily-Migration-6N/FCM-Migration-NewNodesFromGenesis-2.5k-8m/node0005/

**Comment by edward-swirldslabs** [comment] 2023-11-13 20:58
Updated analysis.  The JRS Test Framework ignores the InitTrigger and related errors from node 4 and node 5.   These tests are failing for the reasons indicated in the summary.

**Comment by lpetrovic05** [comment] 2023-11-21 10:17
I think I see what the problem is. These errors get logged all the time, but they are expected for genesis nodes, so they are ignored. When the test fails for a different reason, people mistake the source of the issue, thinking it was the genesis trigger. 
Reasons for failure:
- [original issue](https://github.com/hashgraph/hedera-services/issues/9336#issue-1949942903), the reason for failure is actually `SignedStateSentinel: old signed state detected, memory leak probable.`
- [failure Austin reported](https://github.com/hashgraph/hedera-services/issues/9336#issuecomment-1808449757), the reason for failure is `Reconnect took 24.736 seconds to transmit 359.80681324005127 mb.`
Closing this since its not an issue.

**Closed by lpetrovic05** 2023-11-21 10:17 UTC
