### ISSUE TITLE
Epic: Implement the `hedera-token-service` modules

### ISSUE THREAD

**Issue by rbair23** [hashgraph/hedera-services#4214] opened 2022-11-08 01:10 UTC
- [x] https://github.com/hashgraph/hedera-services/issues/4050
- [x] https://github.com/hashgraph/hedera-services/issues/4027
- [x] https://github.com/hashgraph/hedera-services/issues/4225
- [x] https://github.com/hashgraph/hedera-services/issues/4226
- [x] https://github.com/hashgraph/hedera-services/issues/4227
- [x] https://github.com/hashgraph/hedera-services/issues/4228
- [x] https://github.com/hashgraph/hedera-services/issues/4229
- [x] https://github.com/hashgraph/hedera-services/issues/4255
- [x] #4450
- [x] #4449 
- [x] #4451

Tokens:
- [x] https://github.com/hashgraph/hedera-services/issues/4049
- [x] #4454
- [x] https://github.com/hashgraph/hedera-services/issues/4029
- [x] #4452

**Comment by Neeharika-Sompalli** [comment] 2023-05-10 17:17
Duplicate of https://github.com/hashgraph/hedera-services/issues/5767

**Closed by Neeharika-Sompalli** 2023-05-10 17:17 UTC
Labels: Epic, Modularization
