### ISSUE TITLE
Accounts integrity violated with `accounts.storeOnDisk` enabled

### ISSUE THREAD

**Issue by OlegMazurov** [hashgraph/hedera-services#6846] opened 2023-05-31 17:01 UTC
### Description

An affected node stops after:
```2023-05-31 04:31:21.607 ERROR 161 SignedStateBalancesExporter - Signed state @ 2023-05-31T04:30:00.028323066Z had total balance 5000000000005011866 not 5000000000000000000; exiting ```

### Steps to reproduce

I ran `NftTransferLoadTest` with the load generator (10M accounts, 100M NFTs). Enabled  all `VirtualMaps`, balance exporting. 

### Hedera network

other

### Version

v.0.39.0-SNAPSHOT

### Operating system

Linux

**Comment by OlegMazurov** [comment] 2023-05-31 17:02
It's a regression likely caused by #6741

**Comment by artemananiev** [comment] 2023-06-01 00:37
This is a regression from #6741. Here is how it happens:

1. Version N of a virtual node cache is created
2. Key K is mutated in version N
3. Version N+1 is created. Version N becomes immutable
4. Key K is mutated again, in version N+1
5. Version N+2 is created. Version N+1 becomes immutable
6. Version N is hashed. cache.dirtyLeaves() is called
7. Version N+1 is hashed. cache.dirtyLeaves() is called again
8. Version N is flushed. cache.dirtyLeaves() is called again

At step 7, key K mutation for version N is marked as to be filtered, because in version N+1 it's superseded by the new mutation. Then at step 8, that mutation for version N is not included, and the corresponding value is not flushed to disk.

**Closed** 2023-06-02 22:22 UTC
Labels: P1, Regression, Platform Virtual Map
