### ISSUE TITLE
Modify the release process to use the Semantic Release tool to issue tags and generate release notes

### ISSUE THREAD

**Issue by nathanklick** [hashgraph/hedera-services#11781] opened 2024-02-27 19:39 UTC
## Description

In order to reduce the current friction for the Services Release Manager, the `semantic-release` tool should be implemented to handle the release process including build version number updates, tag creation, and release note generation. 

### Caveats

- The semantic release tooling must be configured to treat breaking changes as minor version increments.

**Comment by rbarkerSL** [comment] 2024-10-29 04:58
duplicate of in-progress issue: #14967

**Closed by rbarkerSL** 2024-10-29 04:58 UTC
