### ISSUE TITLE
Explain and, if possible, flatten the initial "spike" in secTransH seen in regression

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#780] opened 2020-11-18 16:18 UTC
**Summary**
For unclear reasons, the early values of `secTransH` in regression are abnormally large. This distorts the graphs of this statistic and makes them hard to read.

**Comment by noshmody** [comment] 2020-12-08 14:56
Could we be writing out the initial account balances file?

**Comment by anighanta** [comment] 2020-12-10 16:04
Finished profiling Handle Transaction for each transaction we send. Found that the first transaction takes significantly longer time, around 50 times slower than the transactions [ Once JustInTime Compiler generates best possible optimized code after a few transactions]. 

Possible Graphing scenarios to pursue:
1. Skip the first 2 secs from the stats file and graph all of the metrics.
2. Skip the first 2 secs for just the secTransH metric and graph it.
3. Add a new graph that ignores the first 2 secs for the secTransH metric.

**Comment by anighanta** [comment] 2020-12-10 16:58
> Could we be writing out the initial account balances file?

Since we perform  `writing out the initial account balances file` during `init` this cannot explain the spike. Java Just-In-Time compiler is the most probable explanation.

**Comment by anighanta** [comment] 2020-12-23 15:44
Implemented option 3 from [comment](https://github.com/hashgraph/hedera-services/issues/780#issuecomment-742614948) and merged [here](https://github.com/swirlds/swirlds-platform-regression/pull/741). Closing this issue.

**Closed by anighanta** 2020-12-23 15:44 UTC
Labels: Test Development, enhancement
