### ISSUE TITLE
Prepare migration of default branch from develop to main

### ISSUE THREAD

**Issue by rbarkerSL** [hashgraph/hedera-services#16807] opened 2024-11-27 03:26 UTC
## Background

The @hashgraph/devops-ci team is planning to change the default branch on hedera-services from `develop` to `main`. 

- We are targeting Friday, December 20th at 22:00 US Central time for the switch-over.

## Desired outcome

We need a branch that modifies all of the source code, github workflows, scripts, etc. within the hedera-services repository to be set up such that all references to `develop` are re-targets to `main`

**Comment by mishomihov00** [comment] 2024-11-27 13:29
@rbarkerSL In the linked PR you can see an initial version of the branch. The only file that I'm not entirely sure how to change is `docs/maintainers-guide.md`

**Comment by andrewb1269hg** [comment] 2024-12-03 15:59
Related issues:
#16809 
#16808

**Comment by rbarkerSL** [comment] 2024-12-13 20:23
> @rbarkerSL In the linked PR you can see an initial version of the branch. The only file that I'm not entirely sure how to change is `docs/maintainers-guide.md`

I'm not worried about that. I will update that with the rename next weekend.

**Comment by andrewb1269hg** [comment] 2024-12-17 19:16
Closing as duplicate of #16809

**Closed by andrewb1269hg** 2024-12-17 19:16 UTC
Labels: github_actions
