### ISSUE TITLE
Implement `FileService`'s `handle()`-methods

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#4455] opened 2022-12-09 14:57 UTC
### Problem

We need handle()-methods:
- [ ] FileAppendHandler.handle()
- [ ] FileCreateHandler.handle()
- [ ] FileDeleteHandler.handle()
- [ ] FileUpdateHandler.handle()
- [ ] SystemDeleteHandler.handle()
- [ ] SystemUndeleteHandler.handle()

### Solution

Implement the above.

**Comment by nickpoorman** [comment] 2023-04-18 21:02
Duplicate of https://github.com/hashgraph/hedera-services/issues/5517

**Closed by nickpoorman** 2023-04-18 21:02 UTC
Labels: Modularization
