### ISSUE TITLE
Get rid of usages of `ConfigurationHolder` in `platform-sdk`

### ISSUE THREAD

**Issue by imalygin** [hashgraph/hedera-services#11336] opened 2024-02-02 18:16 UTC
### Problem

`ConfigurationHolder` has been deprecated for quite a while but it's still used in `platform-sdk` codebase. 

### Solution

We should get rid of using `ConfigurationHolder` in favor of passing `Configuration` instance as a constructor parameter

**Comment by poulok** [comment] 2024-06-06 16:54
closing as a duplicate of #5670

**Closed by poulok** 2024-06-06 16:54 UTC
Labels: Tech Debt Reduced, Platform
