### ISSUE TITLE
Modularize hedera-util-service

### ISSUE THREAD

**Issue by nickpoorman** [hashgraph/hedera-services#5522] opened 2023-03-08 18:59 UTC
TODO: Fill in details in a similar way to "Modularized HCS implementation" was done. 

https://hips.hedera.com/hip/hip-351

https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/util/UtilPrngTransitionLogic.java

**Comment by Neeharika-Sompalli** [comment] 2023-05-02 03:41
Duplicate of https://github.com/hashgraph/hedera-services/issues/5724

**Closed by Neeharika-Sompalli** 2023-05-02 03:41 UTC
