### ISSUE TITLE
Implement CryptoTransferHandler.validate()

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#4887] opened 2023-02-07 14:06 UTC
Add the precheck logic to CryptoTransferHander.

Each query has a payment `CryptoTransfer` transaction which need to be validated if there are any invalid fields/values in it. 

Currently that functionality to validate is present in `CryptoTransferTransistionLogic.validateSemantics()`.

The functionality from `CryptoTransferTransistionLogic.validateSemantics()` needs to be migrated to `CryptoTransferHandler.validate()`.

**Comment by nickpoorman** [comment] 2023-03-08 19:11
There is currently an adapter and the adapter needs to be removed in a future iteration.

**Comment by Neeharika-Sompalli** [comment] 2023-05-10 17:18
Duplicate of https://github.com/hashgraph/hedera-services/issues/5805

**Closed by Neeharika-Sompalli** 2023-05-10 17:18 UTC
Labels: Modularization
