### ISSUE TITLE
HSCS-PREC-014 Gas/Performance reconciliation of ContractCalls that do Fungible mint/burn

### ISSUE THREAD

**Issue by stoqnkpL** [hashgraph/hedera-services#2474] opened 2021-11-12 10:45 UTC
### Problem

We need sample Solidity contract(s) and EETs to demonstrate that the gas cost of each HTS precompile, when used to exhaust the gas/sec throughput of the network, has an acceptable impact on secTransH.

That is, the secTransH of running ContractCalls that exhaust the gas/sec throttles via HTS precompiles should be low enough that the network retains bandwidth to handle ~2k TPS of CryptoTransfer or ConsensusSubmitMessage.

Verify a client that exhausts the gas/sec throttles by submitting ContractCalls that do only precompiled fungible mints and burns does not disrupt concurrent 2k TPS of mixed CryptoTransfer/ConsensusSubmitMessage.

### Solution

Write EETs that can be used as JRS to validate network stability with production throttles and the above traffic patterns.

**Comment by tinker-michaelj** [comment] 2022-06-17 22:32
Duplicate of https://github.com/hashgraph/hedera-services/issues/2450

**Closed by tinker-michaelj** 2022-06-17 22:32 UTC
Labels: Test Development, hts-contracts
