### ISSUE TITLE
Create testing app for preconsensus event stream

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#5714] opened 2023-03-20 15:30 UTC
Create a testing application that will fail validation if the preconsensus event stream is not present.

- This app should catch situations where a restart causes a transaction to be rolled back
- This app should catch situations where transactions are handled twice on the same state (or state copy)

Eventually, we will want to test the following situations with this app, although we don't need to deploy these tests yet.

- restart
- reconnect
- genesis reconnect

**Comment by poulok** [comment] 2023-03-31 13:41
Duplicate of #5783

**Closed by poulok** 2023-03-31 13:41 UTC
