### ISSUE TITLE
hedera-app comments needed

### ISSUE THREAD

**Issue by kimbor** [hashgraph/hedera-services#5495] opened 2023-03-08 17:47 UTC
- [ ] add javadoc class descriptors for all public classes and interfaces
- [ ]  It's not clear what this method is for [https://github.com/hashgraph/hedera-services/blob/4c7937e541d1699b743908e93da40347f5b06a4d/hedera-node/hedera-app/src/main/java/com/hedera/node/app/ServicesMain.java#L149](https://github.com/hashgraph/hedera-services/blob/4c7937e541d1699b743908e93da40347f5b06a4d/hedera-node/hedera-app/src/main/java/com/hedera/node/app/ServicesMain.java#L149)

**Comment by Neeharika-Sompalli** [comment] 2024-05-15 16:55
Duplicate of https://github.com/hashgraph/hedera-services/issues/12990

**Closed by Neeharika-Sompalli** 2024-05-15 16:55 UTC
