### ISSUE TITLE
VMerkleDual-NDReconnect-500-60m failing while transmitting virtual map

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#8138] opened 2023-08-21 19:12 UTC
Originally documented in https://github.com/swirlds/swirlds-platform-regression/issues/3527

**Comment by artemananiev** [comment] 2023-09-09 00:06
I traced all recent `VMerkleDual-NDReconnect-500-60m` failures back to mid August, all of them are caused by the following issue: https://github.com/hashgraph/hedera-services/issues/8237. There are a couple older failures with different symptoms (e.g. one of them looks like the node went out of disk space), the chances are there were observed before JRS was switch to use MerkleDb instead of JasperDB.

**Comment by artemananiev** [comment] 2023-09-09 00:15
The original issue https://github.com/swirlds/swirlds-platform-regression/issues/3527, which was caused by socket read timeouts, is no longer reproducible, so I'm closing this ticket. If the test starts failing again (after the fix for #8237 is applied), it will be tracked as a separate ticket.

**Closed by artemananiev** 2023-09-09 00:15 UTC
