### ISSUE TITLE
Differential testing PBB: Take event playback branch and "productize" it for general use

### ISSUE THREAD

**Issue by david-bakin-sl** [hashgraph/hedera-services#7620] opened 2023-07-20 02:03 UTC
Matt H has a branch where events can be played back as needed for diff testing; however this is done by invasive changes to the source of the modular node and can't be merged to develop.  This will make it hard to keep the playback capability up-to-date as changes are made to the underlying source.  

This issue: figure out a way to better package this to make this capability usefully repeatable by multiple people and making maintenance easier to keep it working as the underlying node is modified.

Part of _primitive building block_ in #7619.

**Comment by mhess-swl** [comment] 2024-01-12 17:12
Closing as a duplicate of #10946

**Closed by mhess-swl** 2024-01-12 17:12 UTC
Labels: Modularization
