### ISSUE TITLE
Proposal: How to use a context for base operations

### ISSUE THREAD

**Issue by hendrikebbers** [hashgraph/hedera-services#7014] opened 2023-06-09 10:42 UTC
# How to use a context for base operations

This document outlines the concept of a 'global context' that enables all basic facilities to gather and disseminate 
metadata efficiently. The concept leverages several functionalities currently employed in microservice environments, 
mapping these concepts to a modular monolith.

## Definition of a context

When we refer to a 'context', we are speaking of a specific state. This state can be unique to the entire process or
specific to a thread. In HTTP based services such context is often used to store information about the current request.
In our scenario, the context can be leveraged to retain information about a current workflow, such as a transaction.

The data within a context is typically stored as a key-value map, implying that key-value pairs can be conveniently 
stored within a context. For simplicity, it is advisable to store pairs as strings. On this premise, a context can be 
defined by the following API draft:

```java

public interface Context {

    String get(String key);

    void set(String key, String value);

    void remove(String key);

    Stream<String> keys();

}

```

As mentioned, a common use case involves a thread-bound context, meaning that the context is linked to the current thread.
By using `ThreadLocal` this can be easily achieved, enabling static and straightforward access to the `ThreadContext`:

```java

ThreadContext.set("key","value");

```

## The advantage of having context based metadata

The benefit of having a context based metadata is that it can be used by all base facilities for data collection and 
distribution. A common use case is logging, where the metadata from a context can be automatically appended to all 
processed log messages. The following illustrations provides an example of that behavior:

<img width="600" alt="Context based logging]" src="https://github.com/hashgraph/hedera-services/assets/9443847/744982e1-1899-40c8-9f6c-d746de45bf69">

By implementing this, a simple `log.info("Hello World")` call can generate the following log message:

```
2023-06-07T11:50:17.345943 - INFO - Hello World - {spanId=5e337baa-1bb8, nodeId=0x3d4e, thread=Thread-1}
```

In the provided example, the information enclosed within the curly brackets represents the context metadata, which is 
automatically appended by the logger. This pattern is known as *MDC* (Mapped Diagnostic Context) in logging, offering 
numerous advantages. While the log line already offers valuable information, it becomes even more compelling when we 
utilize a log aggregation tool such as *ELK* (Elasticsearch, Logstash, Kibana). With such a tool, we can effortlessly 
search for all log messages related to a specific transaction or workflow. The following illustration provides an 
example of this:

![Kibana logging filter](https://github.com/hashgraph/hedera-services/assets/9443847/a53e9f21-e623-4959-89ca-9ef8613a5040)

As evident in the image, such tools can manage the metadata of log messages (as defined, for example, in the GELF 
format) and offer insightful views and visualizations of this metadata. Similar to Prometheus and Grafana, we can 
develop a Docker-based environment for our own log aggregation tooling, making this functionality accessible 
to all developers.

## How a resource manager can use the context

In the future, we aim to establish a so-called resource manager that will oversee the lifecycle of resources like 
threads. This manager can supply a wealth of information to the context. Let's envision that we have a specific 
resource manager for the platform and another for the node. Whenever a `Thread` is created, the resource manager can 
instantly add pertinent information to the thread context of the new thread. Such information may include the resource 
manager ID, the thread name, and the thread type (native or virtual), for example. As we begin to utilize the [Java 
concurrency API](https://docs.oracle.com/javase/8/docs/api/index.html?java/util/concurrent/package-summary.html) 
more extensively, instead of using the `Thread` class directly, we can also define task information like 
the task type and description in the context. A custom `Executor` can be effortlessly crafted to add such information to 
the context before executing a task. The following code snippet offers a glimpse of what that might look like:

```java

resourceManager.executeTask("checkAccountBalance","This tasks checks the account balance for "+account,()->{
        // do something
        });

```

As long as the `Runnable` that is passed as a lambda expression is executed, the task-related context information 
remains stored within the context:

```java

assert"checkAccountBalance".equals(ThreadContext.get("taskName"));
        assert"This tasks checks the account balance for 0x3de4a".equals(ThreadContext.get("taskDescription"));

```

When a logger is used inside the task we will have a lot of information  is automatically appended to the log message. 
The following block provides an idea of the metadata that could be incorporated into such a log message:

```
resourceManagerId=0x3d4e
thread=Thread-1
taskName=checkAccountBalance
taskDescription=This tasks checks the account balance for 0xf424a
```

## Adding tracing

The previous example already furnishes numerous details that can be used for tracing. Tracing is a common pattern 
utilized by microservice environments to monitor the flow of a transaction or a request across multiple services. The 
following illustration provides an example of this:

<img width="1293" alt="Tracing" src="https://github.com/hashgraph/hedera-services/assets/9443847/dd220e19-d740-45a5-ac97-f1b590922b84">

The illustration depicts a request being processed by multiple services. In each service, a span is created that forms 
part of a trace. The trace ID is used to identify the entire request, while the span ID is used to identify the current 
service. Additionally, a span can have a parent span.

While tracing is predominantly used in a microservice environment, it can also be effectively implemented in a monolith. 
Let's suppose we define start and end timestamps for each task that is executed. With this information, we can easily 
create a span for that task. In such a concept, a span already holds a wealth of information that we could store in the 
thread context. The following illustration provides a generic overview of how this behavior might appear:

![Spans in a monolith](https://github.com/hashgraph/hedera-services/assets/9443847/48af51d9-6614-46cd-aea9-c5883eec1380)

When a logger is used within a span, we will once again have additional information that is automatically appended to 
the log message:

```
resourceManagerId=0x3d4e
thread=Thread-1
taskName=checkAccountBalance
taskDescription=This tasks checks the account balance for 0xf424a

spanId=0xdd56e
spanType=checkAccountBalance
spanParentId=0x67f4a
spanStart=2023-06-07T11:50:17.345943
```

Given that the spans are tied to the resource management of the application, we can effortlessly create a span for each 
task that is executed. In doing so, we don't even need to modify the code of the resource manager. The manager will 
automatically generate a span. If the calling thread already has a span, we can use that span as a parent span. If not, 
we can create a span without a parent span. The following code snippet demonstrates how that might look:

```java
resourceManager.executeTask("executePreHandles","Executes preHandlers for "+transactionId,()->{

        // do something

        resourceManager.executeTask("checkAccountBalance","checks  balance for "+accountId,()->logger.info("Hello World"));

        });

```

In the provided scenario, the log message would contain information about the current span and could even be linked to 
the task that initiated the inner task, as we are aware of the parent span's ID.

## Visualize tracing

Grafana is currently developing a new tracing feature for its platform that can be used to visualize traces. As we are 
already using Grafana, this would be a perfect fit for us. Like any other service, we can offer this functionality 
directly to the developers to examine spans for performance issues. The following illustration depicts an example of 
spans visualized in Grafana:

![Grafana tracing](https://github.com/hashgraph/hedera-services/assets/9443847/08e47308-286b-4010-8a87-93f1301bd886)

To visualize spans, we need to present the span information in a specific format, much like we do with our metrics. 
Open Telemetry already provides a [specification] 
(https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/overview.md) for this. Given that
Open Telemetry is increasingly used within the industry, it would make sense for us to support this format. As the 
tracing in Open Telemetry provides a wealth of functionality that we do not require (information about microservices, 
HTTP requests, etc.), we could offer a more lightweight API that employs Open Telemetry internally.

## Measure performance automatically

Thanks to our metrics API, we can easily measure the performance of each span and span type. Suppose the span API uses 
the metrics API internally and records execution times (average, max, min) for each span type. In doing so, we would 
automatically obtain information about the performance of each span type.

## Going down the rabbit hole: Measure performance of locks

While the approach given is often used to measure the performance of services in a microprofile environment, it provides
all the necessary information and functionality to measure much smaller units. Let's assume we want to measure the 
performance of a lock. We already have a quite robust API for handling locks using the `AutoLock` and our `Locks` 
facade. Currently, creating and using a lock to secure a resource looks like this:

```java
AutoLock lock=Locks.createLock();

        try(var ignore=lock.lock()){
        // use locked resource 
        }

```

Suppose we add a `String` parameter to the `createLock()` method that is used as the type definition of spans created 
whenever the lock instance is locked. Since each span records execution times (average, max, min) in metrics, we could 
automatically gather information about the usage of resources and identify which resources/locks might need refactoring 
for improved performance. The following code snippet illustrates how that might look:

```java
AutoLock lock=Locks.createLock("transactionQueue");

        try(var ignore=lock.lock()){
        // use locked resource 
        }

```

One potential issue when working with small spans is the resulting increase in total number of spans. This could 
potentially lead to complications when visualizing the data. Although the metrics can provide an overall picture of 
each span type's performance, we may still need specific numbers for individual span instances at runtime for 
detailed analysis.

## Making use of JFR

Java 11 introduced the Java Flight Recorder (JFR) API as a part of the JDK, providing a powerful tool to measure Java 
application performance. One of the standout features of JFR is its support for custom events. This allows an 
application to define and trigger custom JFR events during its execution.

These events can be monitored by any tool that supports JFR, such as Java Mission Control (JMC) or IntelliJ.
For instance, IntelliJ's Profiler can be employed to inspect a running application and gather all its JFR events. 
This capability enables us to collect and analyze all the necessary JFR events from a running application with 
relative ease.

Moreover, if we configure our application so that the end of each span triggers a custom JFR event, we can leverage 
these events to scrutinize the performance of a specific span type in IntelliJ by examining each individual event.

**Comment by jsync-swirlds** [comment] 2023-06-09 15:52
A few thoughts.
1. Any kind of global context is a high risk item.  The temptation to misuse the context to carry actual process data (rather than only diagnostic) is high.
   * This can be mitigated by naming (e.g. `DiagnosticContext` rather than `ThreadContext`) and making the "get" methods package-private so it is more obvious that only a restricted subset of classes (e.g. "log" decorators and JFR events) should be reading the data.
1. Threading and lock management is one of the hardest things to get correct.  Adding to the current "resource manager" or "lock" classes (when ideally we would move away from those and use the core JVM classes directly) is not ideal.
1. There are multiple existing excellent span and trace libraries compatible with OpenTelemetry.  What is the value of creating our own solution to the same problem?
1. The paragraph on "resource manager" using this context object has some anachronisms we might discuss to make it more in line with high quality concurrency design.

**Comment by hendrikebbers** [comment] 2023-06-09 17:25
Answering @jsync-swirlds comments:
1. I like `DiagnosticContext` as a name. Having the getter hidden for the base facilities is another very good idea. I will add it to the draft next week.
2.  When talking about "resource manager" I do not mean the tread manager that is used in platform today. That's why I created a new name and even splitted the issues/epics: https://github.com/hashgraph/hedera-services/issues/5801 is about the current Thread manager while https://github.com/hashgraph/hedera-services/issues/6963 will be about the feature (and I hope that I can add some draft content to that issue in near future). When talking about Locks we already use the JVM concurrency API but add some cool stuff (look at `com.swirlds.common.threading.locks.Locks` and `com.swirlds.common.threading.locks.AutoClosableLock`). 
3. Well I do not want to reinvent the wheel. My idea is to create a wrapper around one of that libraries and even private a more minimalistic API since most trace libs provide features that we do not want / need.
4. Yeah, I'm with you. The name came up last year when talking about base functionalities and services. Since I do not know another use case than concurrency handling for that manager I would choose another name, too. Totally open for any suggestions at that point :)

**Comment by hendrikebbers** [comment] 2023-06-09 17:48
The current code playground can be found here: https://github.com/hendrikebbers/context-prototype

**Comment by jasperpotts** [comment] 2023-06-13 23:25
I am mixed on the idea..... I love the idea of being able to use tooling to visualize what is going on in the server 😀 but I have three main concerns.

1. Performance cost, doing any non-critical work per transaction is scary. When we are spending days at other levels of system to optimize by removing a single `if` statement or method call. A single if on a boolean in a hot spot was costing us 15% performance in data parsing.
2. Network bandwidth, unlike normal micro-services where all the logging is sent over a private high speed network. All of ours has to be sent over the same relatively small 1GB public internet link that is shared with customer requests, gossip, streams, backups etc.
3. If that data model fits to what we do. It seems loverly to be able to see all the work items that happen for the context of a transaction. The problem is there is very little that happens for only one transaction. Most things happen on an event or round of transactions or greater level. Also almost all transaction specific work is done on one thread.

If we wanted to dig into a single transaction then it would be cool to see, for example every DB read and write done by that transaction. But if we got to that level we would be having to log a million times a second or more, I just don't think we can scale to that at least for production systems. It would be cool for development/testing time if it could be switched off at zero cost for production.

Now at another scale this might be more possible and helpful. What if we thought about it at the task level, that seems like an amazing use case for JFR tracing.  Task being one item of work done on a background thread. At the moment I think what we do even at that level is maybe too granular to be able to log cost effectively. But maybe it is ok for 90% of cases and a few are so hot that it can't be done. We have lots of problems today about balancing tasks across CPUs, queue sizes, task granularity and task synchronization points. If we had nice ways to see what was happening then it might be easier to diagnose and improve. When Richard & I were working on Database performance we spent a month or more looking at JProfiler thread graphs and balancing how the work was split between threads so they could all be busy without spending most of their time waiting for other threads.

The other thing is as we get more experience I think the way we think about thread usage has changed some. We started with the philosophy of we have limited RAM, Disk bandwidth but plenty of CPUs so the more we can do in background threads the better. Now we are at the point where we are getting performance reports from Oleg that we have too many threads and we are wasting a large amount of CPU time in thread synchronization. So threading is a fine balancing act. The new thinking Richard & I have been discussing is should we just have a few critical threads and all other tasks in the system use one shared thread pool. Maybe the default fork join thread pool or maybe a different one. Or maybe one for fork join style and one for fire and forget tasks. If we use a common pool, we loose the visibility we get from thread names, so this is where tracing context could help.

**Comment by rbair23** [comment] 2023-06-14 00:48
Awesome issue @hendrikebbers & @timo0! I really love the effort and transparency. Super cool!

When I have thought about this in the past, I thought: JFR for profiling, tracing for transaction tracking. I share Jasper's concerns around performance. I think we will have problems if we trace at too granular a level (and definitely if we log at that level).

## MDC Context Logging

Overall, I like this idea. The context seems simple and lightweight and shouldn't add much to logs, in general. In production it adds probably very little, because this level of detail is generally appropriate for DEBUG but not INFO+ level logging (i.e. our production logs should be sparse, containing only INFO+ levels. ERROR/FATAL should basically never happen, WARN should be infrequent, and INFO should be limited to things like "connected to new peer", "saving state to disk", and other such infrequent but important operational items, and not contain per-round or per-event or per-transaction information, since logging at that frequency is just too expensive).

Of course MDC logging was the root of the most recent spate of Log4j bugs, since they have an MDC capability coupled with LDAP, but this is not a problem for us since all context is just a map of strings, and none of those strings will hold sensitive data (which is critical, of course).

## Tracing

Tracing of a transaction from ingestion on a node through to the mirror node would be very interesting. We *may* be able to do this at 10K TPS, but we'd have to validate that. There have been times in production, or in development, where we've wished we had some way of tracing a single transaction. Not normally for performance reasons, but more for just understanding when it hit each part of its path and what the outcome was.

Just today as I thought about this more, I also thought about maybe tracing a hashgraph event. I think that would also be interesting.

Other than that, I haven't considered any other use cases compelling enough to warrant the work. What are the most compelling cases for using tracing? It has to be somehow course grained enough to not be a performance bottleneck but still be useful.

Transaction tracing is actually difficult because of what it means to be a transaction. In our system, a transaction is sent to a node. But the "same" (slightly modified) transaction can be sent to multiple nodes -- each duplicate "transaction" has the same body and data, and the same transaction ID, but a different target node and signature. Each is distinct, and yet, represent the same actual "transaction body data".

For example, I may have a crypto transfer where I am transferring an NFT to Hendrik. I encode this as a "transaction body data" and create a transaction ID for this transaction. Then I create a "transaction body" with that ID and data, and I set the node to the IBM node. I sign all of that and send that "transaction" to IBM. I then create a second "transaction body" with the same ID and data, but this time set the node to the Google node and sign the transaction and send it to the Google node.

We now have two distinct transactions in the system (distinct because one is targeted at the IBM node and one at the Google node), but both with the same transaction ID and both representing the same logical transaction -- transferring this NFT to Hendrik.

So when we talk about tracing a transaction, we have to think about two distinct use cases:
  - Tracing these two distinct transactions independently
  - Tracing the "user transaction" (the NFT transfer).

In addition, each node has its own traces. Suppose I have another simple crypto transfer, and this time I will transfer 10 hbars to Timo. So I create the transaction body data and transaction Id, create a transaction body with those things plus I target the Swirlds node, and I sign the transaction and send it to the swirlds node. The swirlds node is going to record a span for "ingestion" of the transaction -- this is the true start of the lifespan of this transaction on its journey through our system.

Then it gossips this transactions as part of an event to all the other nodes. At some point the swirlds node will pre-handle this transaction. And once gossiped, each node that sees this event will pre-handle this transaction as well. The time at which each node does this will be different, as will the duration of that span. Then each node will at some point handle this transaction, though once again the wall clock time this happens at will be different for each.

Then the transaction will be bundled into a record file, with potentially up to 2 seconds duration from when the transaction was handled until the record is closed. Then that record is shipped to an S3 compatible bucket and downloaded by the mirror node. The mirror node will parse the record and ingest the transaction into its database, and could then produce the final span for that "user" transaction.

Duplicate transactions have a different life -- they will be pre-handled, they will get to "handle" and be rejected as duplicates, and the payment for that duplicate will be handled and written to a record file and made available to the mirror node as well.

I am not sure OpenTracing is setup to handle this kind of path we have for transactions? Maybe it does! I don't know what the performance ramifications are. I think tracing transactions is probably the most useful trace we could produce. To be honest, I'm not sure it is useful enough to justify the cost -- depending on what the cost is.

We could trace Events, which would be much simpler.  An event is generated on a particular node and sent to all other nodes. Events are pre-handled, so we could easily get a span for the pre-handle part of its lifecycle. And multiple events are bundled into a round -- at the services level I don't think we know which events are in each round, so we aren't able to trace it much further than that. So maybe events are not all that interesting in the end.

## JFR

I really like the idea of exploring JFR. If it is true that we can leave it enabled in production with minimal overhead, then we could have some method for triggering a JFR dump (probably through NMT -- the node management tool), then it would be useful in many environments including production. Being able to go to production and get a profile dump, even when things are going well, would be very insightful. I'm interested in @OlegMazurov's thoughts on using JFR.

**Comment by steven-sheehy** [comment] 2023-06-14 17:54
You have to be [careful](https://spring.io/blog/2023/03/28/context-propagation-with-project-reactor-1-the-basics) about context propagation relying upon `ThreadLocal` since this construct breaks down with Project Loom and its lightweight threads that are not based upon pthreads. It also breaks down with reactive libraries like Project Reactor or RxJava where a single request can flow through many distinct threads. It even breaks down when using your own thread pools in application code to parallelize work unless you manually propagate context.

I agree with the statement that the industry is migrating from OpenTracing to OpenTelemetry and we should support the latter.

Performance of tracing is manageable if sampling is used to trace a very small subset of requests since you can always reduce the sampling percent lower and lower until its not noticeable.  Tracing should never be done at 100% as that is a huge performance penalty. I like the idea of tracing a transaction (regardless of distinctness of transaction ID) at its system ingress/egress points, but might be overkill to trace local DB updates.

I know we are hesitant to depend upon more libraries, but the [Micrometer Observation](https://micrometer.io/docs/observation) library was created to handle these problems while remaining performant. It handles the difficult problem of context propagation across thread boundaries. It handles tracing with its programmatic Observation API to start and stop spans. It even can produce metrics for those traces simultaneously so you don't have to pay the performance penalty of doing separate timings for metrics and traces. Mirror node plans on using its Spring Boot 3 [support](https://spring.io/blog/2022/10/12/observability-with-spring-boot-3) to add tracing at some point. The library helps abstract away:

 * OpenTracing vs OpenTelemetry
 * Prometheus vs Elasticsearch
 * Removes the need to generate or populate span/trace IDs
 * Associating logs to spans/traces
 * Declarative sampling percentage
 * Handle high cardinality key/values

**Closed** 2023-11-20 15:35 UTC
