### ISSUE TITLE
Crypto-Recovery-300-21m  failed with corrupt fees in state

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#1357] opened 2021-05-03 16:35 UTC
**Summary of the defect**
`Crypto-Recovery-300-21m ` test failed on all the validators. But the root cause looks like it is caused because there is a fatal exception in `hgcaa.log` caused by corrupt fee schedules in state. Need to investigate further why it is caused.

```
Node 0 has exception:- Corrupt fee schedules in saved state, unable to continue!
Node 0 has exception:- Fatal precondition violated in HederaNode#0!
Node 1 has exception:- Corrupt fee schedules in saved state, unable to continue!
Node 1 has exception:- Fatal precondition violated in HederaNode#1!
Node 2 has exception:- Corrupt fee schedules in saved state, unable to continue!
Node 2 has exception:- Fatal precondition violated in HederaNode#2!
Node 3 has exception:- Corrupt fee schedules in saved state, unable to continue!
Node 3 has exception:- Fatal precondition violated in HederaNode#3!
```

**How to reproduce (if possible)**
Slack link:https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1619938804168500
Slack Summary link : https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1619943970058200

**Comment by tinker-michaelj** [comment] 2021-05-13 20:55
Duplicate of #1361

**Closed** 2021-07-12 16:48 UTC
Labels: Regression, bug
