### ISSUE TITLE
HalfDiskHashMap:	Failed to read / update bucket

### ISSUE THREAD

**Issue by edward-swirldslabs** [hashgraph/hedera-services#12828] opened 2024-04-15 21:44 UTC
Failed JRS Test: VMerkleDual-NDReconnect-500-60m
Data Folder: http://35.247.76.217:8095/swirlds-automation/release/0.49/4N/Reconnect/20240412-094024-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/
swirlds-log: http://35.247.76.217:8095/swirlds-automation/release/0.49/4N/Reconnect/20240412-094024-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/swirlds-logs.html

Node 3 problem

There were several types of exceptions, but this was repeated: 
```
HalfDiskHashMap:	Failed to read / update bucket
java.lang.IllegalArgumentException: Unknown bucket field: 2
	at com.swirlds.merkledb.files.hashmap.Bucket.readFrom(Bucket.java:334) ~[swirlds-merkledb-0.48.0.jar:?]
	at com.swirlds.merkledb.files.hashmap.BucketSerializer.deserialize(BucketSerializer.java:142) ~[swirlds-merkledb-0.48.0.jar:?]
	at com.swirlds.merkledb.files.hashmap.BucketSerializer.deserialize(BucketSerializer.java:35) ~[swirlds-merkledb-0.48.0.jar:?]
	at com.swirlds.merkledb.files.DataFileCollection.readDataItem(DataFileCollection.java:526) ~[swirlds-merkledb-0.48.0.jar:?]
	at com.swirlds.merkledb.files.DataFileCollection.retryReadUsingIndex(DataFileCollection.java:550) ~[swirlds-merkledb-0.48.0.jar:?]
	at com.swirlds.merkledb.files.DataFileCollection.readDataItemUsingIndex(DataFileCollection.java:636) ~[swirlds-merkledb-0.48.0.jar:?]
	at com.swirlds.merkledb.files.hashmap.HalfDiskHashMap.readUpdateQueueBucket(HalfDiskHashMap.java:485) ~[swirlds-merkledb-0.48.0.jar:?]
	at com.swirlds.merkledb.files.hashmap.HalfDiskHashMap.lambda$endWriting$2(HalfDiskHashMap.java:433) ~[swirlds-merkledb-0.48.0.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

and 

```
VirtualHasher:	Failed to wait for all hashing tasks
java.nio.BufferUnderflowException: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:542) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:567) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:653) ~[?:?]
	at com.swirlds.virtualmap.internal.hash.VirtualHasher.hash(VirtualHasher.java:502) ~[swirlds-virtualmap-0.48.0.jar:?]
	at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.lambda$prepareReconnectHashing$4(VirtualRootNode.java:1483) ~[swirlds-virtualmap-0.48.0.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.nio.BufferUnderflowException
	at com.hedera.pbj.runtime.io.buffer.BufferedData.checkUnderflow(BufferedData.java:499) ~[pbj-runtime-0.8.3.jar:?]
	at com.hedera.pbj.runtime.io.buffer.BufferedData.getInt(BufferedData.java:419) ~[pbj-runtime-0.8.3.jar:?]
	at com.swirlds.merkledb.files.hashmap.Bucket.getBucketIndex(Bucket.java:171) ~[swirlds-merkledb-0.48.0.jar:?]
	at com.swirlds.merkledb.files.hashmap.HalfDiskHashMap.endWriting(HalfDiskHashMap.java:444) ~[swirlds-merkledb-0.48.0.jar:?]
	at com.swirlds.merkledb.MerkleDbDataSource.writeLeavesToPathToKeyValue(MerkleDbDataSource.java:1243) ~[swirlds-merkledb-0.48.0.jar:?]
	at com.swirlds.merkledb.MerkleDbDataSource.saveRecords(MerkleDbDataSource.java:527) ~[swirlds-merkledb-0.48.0.jar:?]
	at com.swirlds.virtualmap.internal.merkle.AbstractHashListener.flush(AbstractHashListener.java:176) ~[swirlds-virtualmap-0.48.0.jar:?]
	at com.swirlds.virtualmap.internal.merkle.AbstractHashListener.onNodeHashed(AbstractHashListener.java:141) ~[swirlds-virtualmap-0.48.0.jar:?]
	at com.swirlds.virtualmap.internal.hash.VirtualHasher$ChunkHashTask.exec(VirtualHasher.java:237) ~[swirlds-virtualmap-0.48.0.jar:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
```

**Comment by artemananiev** [comment] 2024-04-16 00:17
This is a duplicate of https://github.com/hashgraph/hedera-services/issues/12311

**Closed by artemananiev** 2024-04-16 00:17 UTC
