### ISSUE TITLE
Implement FilesService's `prehandle()`-methods

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#4028] opened 2022-10-06 21:54 UTC
### Problem

We need preHandle()-methods:
- [ ] FileAppendHandler.preHandle()
- [ ] FileCreateHandler.preHandle()
- [ ] FileDeleteHandler.preHandle()
- [ ] FileUpdateHandler.preHandle()
- [ ] SystemDeleteHandler.preHandle()
- [ ] SystemUndeleteHandler.preHandle()

### Solution

Implement the above.

**Comment by nickpoorman** [comment] 2023-04-18 21:02
Duplicate of https://github.com/hashgraph/hedera-services/issues/5517

**Closed by nickpoorman** 2023-04-18 21:02 UTC
Labels: Modularization
