### ISSUE TITLE
HCS Performance Profiling  - On Mainnet

### ISSUE THREAD

**Issue by noshmody** [hashgraph/hedera-services#519] opened 2020-09-03 21:46 UTC
Profile HCS performance (on `0.8.0-rc1` tag) the the following levels....
General guidlines
-  Initially try with AWS, 4-node, single region
-  Then test on AWS, 13-node, globally distributed  
-  C2C < 10 secs

- [x] Size of HCSSubmitMessage with which we achieve with 5k TPS
- [x] Increase TPS in increments of 0.5k (reducing message size to achieve required TPS)
- [ ] Confirm HCS 256, 512, 1024 byte messages on Mainnet

**Comment by Neeharika-Sompalli** [comment] 2020-09-21 16:46
| HCSSubmitMessage Byte Size  | Number OfNodes inNetwork | Max TPS achieved |
| ------------- | ------------- | ------------- |
| 256 |   |   |
| 512 |   |   |
| 1024 |   |   |
| 2048|   |   |
|  |   |   |
|  |   |   |
|  |   |   |
|  |   |   |

**Comment by Neeharika-Sompalli** [comment] 2020-09-21 18:12
![image](https://user-images.githubusercontent.com/52669918/93804490-fd232480-fc0b-11ea-9328-b47aaebbf550.png)

17% of ServicesState.handleTransaction is taken by `UnsupportedOperationException`

**Comment by atul-hedera** [comment] 2020-09-23 14:55
What is the maximum message size on the 13 node global network that will give us C2C in a reasonable range (3-4 seconds) and will give us the max throughput (close to 10K)?

**Comment by Neeharika-Sompalli** [comment] 2020-09-24 03:52
> What is the maximum message size on the 13 node global network that will give us C2C in a reasonable range (3-4 seconds) and will give us the max throughput (close to 10K)?

@atul-hedera TPS is limited to a max of 8K TPS. With 128 bytes message size lowest C2C of 6-10 seconds is achieved. It looks like C2C can't be reduced further as its caused by network latency.

**Comment by Neeharika-Sompalli** [comment] 2020-10-08 15:06
Closing this issue as profiling is complete and data is recorded in the issue.

**Comment by noshmody** [comment] 2020-11-11 17:31
Profile HCS Performance on Mainnet for the Message sizes listed below.

1. 256 Bytes
2. 512 Bytes
3. 1024 Bytes

Test Characteristics
1. Use account 0.0.950 to pay for txns (make sure it is funded)
2. Use clients in AWS regions where Mainnet nodes are
3. Collect Mainnet CSVs for duration of test - DevOps
4. 10 minutes test 
5. C2C should not exceed 10 seconds

**Comment by Neeharika-Sompalli** [comment] 2020-12-02 00:13
@atul-hedera @donaldthibeau   From the above table of results from test on mainnet, for `1024 byte` message size `Max C2C` is `~6 secs for 3000 TPS`. Should a test be done with higher TPS?

**Comment by lbaird** [comment] 2020-12-02 00:56
If the results are similar on another network, then further testing would be better to do on that other net.

________________________________

**Comment by Neeharika-Sompalli** [comment] 2020-12-04 15:48
Closing the issue as all the information is recorded from mainnet. Will be re-opening this issue if any more information is needed.

**Closed by Neeharika-Sompalli** 2020-12-04 15:48 UTC
Labels: enhancement
